image: ruby:2.6.5

variables:
  JEKYLL_ENV: gitlab
  LC_ALL: C.UTF-8

before_script:
  - ruby --version
  - gem install therubyracer
  - gem install bundler
  - bundle --version
  - bundle install

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - gitlab
