title: six-two
author: six-two
description: >-
  Just a simple website with my contact details.
baseurl: ""
url: ""

email: info@six-two.dev
github_username:  six-two
gitlab_username:  six-two
telegram_username:  six-two
hackerone_username: six-two

js_path: /assets/js/
img_path: /assets/img/
css_path: /assets/css/

theme: minima
feed:
  path: /please_ignore_this_file.xml

plugins:
  - jekyll-sitemap
  - jekyll-minifier

# Encryption stuff
ctd-prompt: "Password required"
ctd-tries: 3
ctd-bank-eur: "eyJpdiI6ImdFb1RqTzdhK1pCY0FMbVpHSFE1ZVE9PSIsInYiOjEsIml0ZXIiOjEwMDAwLCJrcyI6MjU2LCJ0cyI6NjQsIm1vZGUiOiJjY20iLCJhZGF0YSI6IiIsImNpcGhlciI6ImFlcyIsInNhbHQiOiI0akdxVXhXa2F6ND0iLCJjdCI6IjM0aVlydjBXejgzZE4vOElORFpMR0tTVVp0S3g4Vm5lMCtrS3FpQnZGQ1F6ZnVXNUVlcDVRK0w5NiszZzFCZVZwN3RWeVcvR04zSXQxRmp0Q3dTaUF4UXpOY1V0cUpRSERpdWRTQVBsTy8ySFROdzBRb2FQUzBlVEZLcUFBU0pNV1NQUE1kbmhxYUtsQk1hU1ZnZmkwaVFBR1djei9kc25DN05wanJhanc5WEZLTE5rdGQ0dXNRWmxDTE9vSWEwY282NUM4ZUJjMUdWeGpZZlA1U3VpbWxESFJnMVVEaDFXRTBnRloxNDUxbWlIZHY5T0hDS05aOTBiYVVxL2xUbXBTM3U0M0llcUxIaDk1M2VQSnRCT3NTR2NqRGZtSWE1WHRRNnA0bXZIUzljTTdrV2tMd091QlhTNGJTN3UzQWJVQ00ralgvZVZLa3Zmd0ZiWEZaUmdQTnd1WEhLVGZaanptbEFGUXRpeFNvUy9jdjc0WGFoditIMWJXRERzT1hVNVBFQ0ErT1NzSHMxTWlISlJyTTloaTA4M2hsVjl6OWlzMEVzU3FDUWYvUG1OSDZFTVB1Z3pNclhwdWN6YkVIeklBVjRFM0Z5czhDSTF4dllrcEpXVVF3QkVNYnZDTzV6SnBUSy9LV1E9In0="
ctd-bank-usd: "eyJpdiI6IjMwZGZpWHI5bmdmOUkrL3RkaWE5bFE9PSIsInYiOjEsIml0ZXIiOjEwMDAwLCJrcyI6MjU2LCJ0cyI6NjQsIm1vZGUiOiJjY20iLCJhZGF0YSI6IiIsImNpcGhlciI6ImFlcyIsInNhbHQiOiJJSDFlQU14a0NaMD0iLCJjdCI6ImF1eHkyN1dGRUw5S0EvcFFRVWh3MWM4SkpYcitpVWs4MGZOZ3gvaXNEdHRLMU1mL3hEV2I2ekdibFNmR2huYkFxNmZGSWo4YVZYWjBIZi9WN1BlSUJQcmpCYzJhNmluVE9WcnNqY0VtdCtSUkZWclhHVnlkWTZONDlITFcvdTdXbHZ1eHFXQTdnWFdZMzlIMnEvTzluZkdsN0J4TWlFSnl2TTg3aWdlRmgydmJ5cEc5elRIYTNrRkg1N1ZveDYwSHhGWE9DSVJkNkFNNVp4UW50UDRHY2hwNkIwVG4xdDFiWUpReTdnYzZqd3Y2YUsxTm96cUt2d3puSjVmcDM4bk9POHhNbHk2WnBEamhzcGh0WlI1N0VUd0trMVNjdytvSVcwczkwb3Ixb1VDdDVhK3dsUjRVMGNYMTBWeEhqZ2NGNG9JN1l6ZnlUZTlJbVVQUVRPL3FJSXhRRG1UanNyOWpVTUEvSU1kMmd3UUZZYUZvMXgyQWxnMXpNNDVGNXFVbnYrRGRBbXRFU3pIVDNJVnJlbG4wZFA0RGh4cTgxRHNwbk0wN3ZSZGdkRmdla0craU5ZTVlKUFE1N1paUE9NU1haTmJOQitscXpuYWZyS25FUlBZcklkU2F5QUs3czFCaG5LbW5FL3lpdWVKVzg3WmkyWlZ3ZnI3cHp5VXlqTE14d3pqVklQN1NlNjZvRURXS3FSOTRLWlpkNUhGWnVtdTVwOEJ4RlphZjZ0OWFvU2FlbE42SXpQRWt0Q3hkK0FpMUxxYy9Wdz09In0="
ctd-bank-nzd: "eyJpdiI6ImhUVllvMGxOVDZRQm9KS01nUStNNGc9PSIsInYiOjEsIml0ZXIiOjEwMDAwLCJrcyI6MjU2LCJ0cyI6NjQsIm1vZGUiOiJjY20iLCJhZGF0YSI6IiIsImNpcGhlciI6ImFlcyIsInNhbHQiOiJabjNWUGpnazhSVT0iLCJjdCI6IkVCelBRZm04TjcxM2VEVEEyT1hiSXoyVmpTYjBIU0kxWVZpbjJCbUYvcnpmbmNvTmxtTDFUWkNOTzVyVlk4b1ZSdlZRVkhTdFhSa2NVNDIyN2FPVDlVRUpoM3BDV1ROcjVranhpekVtRkt2RXFLZTB1OGUzM2xHazl4K2ZhZ2cwTkRjODFVYmVta0FUUHdGVnZKWFpMWjRsR2ZxcjRpM2Eza3g0STNKb0FwaEU5ZnVWUkFCampjNXBoQnpJbHU0TzRCb3NDT0Y5Qlp0aVV1Yk03QVdIV25UK28zeUlJTU5Ea3lRa2ZIOURDUzlWcS9vM2w3MEFDQXdZR005a0k0MTExRlV5Umo2SFU4aVBTVGVNMnBLcEljN1o2eVpmWEdESzdMamVOY09sbytUcTVoZUFxdlZSTTdMN2ovWlJDTk5GNlFBekZnVFpOTGc5VEl0ejQyTitjRVB4bnRFaXZSOTZnK1p2SWxvLzRKTGkifQ=="


# Minify html, css, js, ...
jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  compress_css: true
  uglifier_args:
    harmony: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .bundle
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
